### ISSUE TITLE
Could not get import in groups

### ISSUE THREAD

**Issue by ladlavj** [codecutout/terraform-provider-powerbi#11]
go test fails after creating 
resource "powerbi_pbix" "example" 
it complaints 
Error: Get "https://api.powerbi.com/v1.0/myorg/imports/16039689-b2ff-4755-97d5-2aecc77ebb69": status code '403 Forbidden' with body {"Message":"API is not accessible for application"}

seems it must try bellow group URL instead of above: https://api.powerbi.com/v1.0/myorg/groups/{groupId}/imports/16039689-b2ff-4755-97d5-2aecc77ebb69

I found that function is no where used in by browsing the code.
**WaitForImportInGroupToSucceed** is not used and instead **WaitForImportToSucceed** used in resource_pbix.go as default

Unfortunately, I don't have goLang knowledge to fix it myself.. request you to please fix it.

**Comment by ladlavj** [comment]
I Think all API calls are without /groups/<group ID> which means will only work on My Workspace.

**Comment by alex-davies** [comment]
Ive found you don't need to use the groupid when fetching items (imports, reports, datasets) it will fetch from whatever worksapce it is in. This however is not true when writing in which omitting a groupid puts it in "My Workspace"

There are integration tests that demonstrate creating pbix imports into a workspace so there must be something different in your particular use case

Could you provide the terraform you are using and confirm what permissions the user you are using has?

**Comment by ladlavj** [comment]
My terraform is as same as in your example.

I've created an Azure application with all required PowerBI API permissions including granted admin consents. In my case, I'm generating authorization token through "client_id", "client_secret" and "tenant_id" but "grant_type=client_credentials"; I can't use Username and password because my user is MFA enabled.

My Power BI tenant admin assigned this "Azure application" bellow permissions
1. Tenant settings -> Developer settings -> Allow service principals to use Power BI  APIs
2. Tenant settings -> Create a workspace
3. Capacity settings -> Contribution access to PowerBI Capacity (premium)

can you suggest what changes should I make to use this provider

**Comment by alex-davies** [comment]
Unfortunately the powerbi API only supports client_credentials. Which means you need a real user with a username and password configured, and that user needs to have MFA turned off.

I typically create a new user dedicated to publishing powerbi reports and use him as a 'service user'

It is odd that you are getting the error that you are though? are you passing empty strings as username or password? or are you passing real credentials but with MFA enabled?

**Comment by alex-davies** [comment]
Actually I was mistaken there is now support  for service principal with client_crediential authentication. 

Currently the provider only password authentication but will look to add support for client_credential authentication

**Comment by ladlavj** [comment]
Though I do not have go lang skills, I've made an attempt.

https://github.com/codecutout/terraform-provider-powerbi/pull/12

**Comment by alex-davies** [comment]
Provider now supports client_credential authentication
