### ISSUE TITLE
Terraform is looking for provider's updates from incorrect namespace

### ISSUE THREAD

**Issue by maxchirkun** [codecutout/terraform-provider-powerbi#13]
I'm trying to use your provider and have faced an issue with the `terraform init` step. Terraform tries to find the provider in the `hashicorp/` namespace instead of `codecutout/`. Could you please take a look and give any suggestions on this?
I created a test playground [here](https://github.com/maxchirkun/tf-power-bi-provider-issue)

![image](https://user-images.githubusercontent.com/10232597/102232318-00266c00-3f00-11eb-9f9f-35982d54fe2e.png)

Also, I'd like to take this opportunity to ask you about your plans for improvements in the provider and maybe you are going to pass some validation of your provider from the Hashicorp team to get an official signature if possible?

By the way, I'm very interested in the next features:
- rebind report to using another dataset
- share access to the created workspace

Looking forward to hearing your reply!

**Comment by alex-davies** [comment]
See the installation section of the readme https://github.com/codecutout/terraform-provider-powerbi#installation

Prior to terraform 0.13 only official hashicorp providers could be automatically downloaded automatically. Installation instructions are present for both 0.13 as well as the steps need to get it running prior to 0.13
