### ISSUE TITLE
Add to Terraform Registry

### ISSUE THREAD

**Issue by abergmeier** [codecutout/terraform-provider-powerbi#2]
For ease of installing, add this provider to Terraform Registry. Pretty please.

**Comment by alex-davies** [comment]
On my TODO list. I only discovered the registry existed shortly after I completed the initial development. 

Need some minor tweaks to the documentation to make it compliant and some build script changes to get it publishing. This might be a reason to create a makefile

**Comment by alex-davies** [comment]
Provider has been added to the registry 

https://registry.terraform.io/providers/codecutout/powerbi/latest/docs
