### ISSUE TITLE
Unable to refresh state if PBIX file contains no dataset

### ISSUE THREAD

**Issue by alxy** [codecutout/terraform-provider-powerbi#27]
I have no idea how it is possible, but it seems that you can actually create PBIX files that do not create a dataset. That means, that `datatset_id` is empty in these cases. While it isn't much of an issue for initial creation (this attribute is just null in the state file), it is a  problem for succeeding updates to the infrastructure, as the refreshing step fails with the following error:

```
Error: Get "https://api.powerbi.com/v1.0/myorg/datasets//parameters": status code '404 Not Found' with body {"error":{"code":"ItemNotFound","message":"Dataset parameters is not found."}}
```

The error is kind of obvious, as the URL is build of the parameter `datatset_id` which is empty in this case.

I have no idea how you can create such PBIX files (and I cannot share the one I have right now because of intellectual property), but I will try to debug it further and let you know.

**Comment by alxy** [comment]
So, I have in investigated this further and it seems when you actually make use of [PowerBI datasets](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets) and connect your report to a dataset, then on upload/publish to the service it will not actually create another Dataset.
If you just create a report and not use any PowerBI dataset it will create the dataset automatically.
The following image shows a PBIX with no dataset connection configured (My PBIX) and another report which uses a dataset connection (My Report):
![image](https://user-images.githubusercontent.com/2057062/106892616-98fd8a80-66ec-11eb-965c-8e957e4d16b0.png)

**Comment by alxy** [comment]
I think from an interface perspective the following would made the most sense:
```terraform
resource "powerbi_workspace" "myworkspace" {
  name = "My Workspace"
}

resource "powerbi_pbix" "mydataset" {
  workspace_id = powerbi_workspace.myworkspace.id
  name         = "My Dataset"
  source       = "./dataset.pbix"
  source_hash  = filemd5("./dataset.pbix")
}

resource "powerbi_pbix" "myreport" {
  workspace_id = powerbi_workspace.myworkspace.id
  name         = "My Report"
  source       = "./report.pbix"
  source_hash  = filemd5("./report.pbix")
  dataset_id   = powerbi_pbix.mydataset.dataset_id
}
```

Where we have an optional dataset_id parameter to pass the dataset id.

**Comment by alex-davies** [comment]
As much as I would like to be able to modify the dataset of a PBIX report is using I don't think the APIs allow that.

However you have discovered a legitimate bug, if we do not have a dataset in our PBIX we should not try to  do any of the dataset operations. This should be a relatively easy bug fix (a few nil checks on dataset_id) 

Ill try have a look into this in the coming week

**Comment by alxy** [comment]
Yeah, I realized that as well when looking at the API. Thanks for looking into it, though :)
I think its probably a matter of not trying to fetch dataset details when `dataset_id` is null.
