### ISSUE TITLE
[FEATURE REQUEST] workspace import

### ISSUE THREAD

**Issue by mikemowgli** [codecutout/terraform-provider-powerbi#71]
I have a bunch of workspaces manually created by users. I'd now like to bring more structure and automation, and manage them as code. Unfortunately, it's not possible to import them. And obviously I cannot delete and recreate them, since I'd then lose all their content.

**Comment by EatZeBaby** [comment]
![image](https://user-images.githubusercontent.com/6329364/179194019-733eb280-d965-4dad-8748-1b50279a7948.png)
I just tried on my end and it seems to work.
The Workspace ID is the UUID you can find in the URL after _groups/_

If you use Powershell, you can also get the IDs of all your workspace with the Cmdlet ```Get-PowerBIWorkspace -All  ```

![image](https://user-images.githubusercontent.com/6329364/179194692-9888b394-679a-4df4-ba7d-35cd6100f43d.png)

**Comment by mikemowgli** [comment]
Sorry for not replying. ths was out of my radar.
I just tried, and this is what I get:
`
terraform import powerbi_workspace.tamers_pbi_workspace[\"Data\ Tamers\ -\ Internal\"] "dfdbREDACTEDb94"
[...]
Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "powerbi_workspace.tamers_pbi_workspace[\"Data Tamers - Internal\"]", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that
│ the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.`

I of course checked that the workspace exists, the ID is correct, and the provider's config has permission over this workspace.

**Comment by mikemowgli** [comment]
Ok, I got it. Here's the explanation:
For terraform to import my workspace, I manually added Admin rights to the Service Principal on the workspace. Then it was failing to import because it seems that Power BI takes quite some time to take new permissions into account. So trying later just fixed it.
Closing. Thanks for the support. The import should probably documented though.
